spring.application.name=dat251-greengafl

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.url=jdbc:postgresql://localhost:5432/greengafldb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=very-secret-secret-i-swear-it-has-to-be-length-32-for-some-reason
app.jwt.expiration-millis=10000000
